# Generated by Django 3.0.6 on 2020-06-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_title', models.CharField(default='', max_length=100)),
                ('course_desc', models.CharField(default='', max_length=1000)),
                ('course_outline', models.CharField(default='', max_length=2000)),
                ('course_fee', models.IntegerField(default=0)),
            ],
        ),
    ]
