# Generated by Django 3.0.6 on 2020-07-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidiates',
            fields=[
                ('candidiate_id', models.AutoField(primary_key=True, serialize=False)),
                ('candidiate_name', models.CharField(default='', max_length=100)),
                ('candidiate_email', models.CharField(default='', max_length=50)),
                ('candidiate_number', models.IntegerField(default=0)),
                ('candidiate_city', models.CharField(default='', max_length=50)),
                ('course_id', models.IntegerField()),
            ],
        ),
    ]
