# Generated by Django 3.0.6 on 2020-07-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_candidiates'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_img',
            field=models.ImageField(default='', upload_to='MyApp/images'),
        ),
    ]
