# Generated by Django 3.0.6 on 2020-07-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_course_course_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_name', models.CharField(max_length=50)),
                ('review_email', models.CharField(default='', max_length=30)),
                ('review', models.CharField(default='', max_length=1000)),
                ('review_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
